### PR TITLE
Complete PT-BR translation

### PR DESCRIPTION
**Pull request by Fibonacci5813**
Full translation of both requested files into Brazilian Portuguese (PT-BR). Made corrections to the story based on typos from the english transcription as well as fixing mistakes pointed by the community in the english transcription. Also its my first time doing this so if i'm doing something wrong on regards to the Github please let me know.

### CODE REVIEW

**Comment by dtzxporter** [comment]
I'll check it out and post a review if anything needs a quick tweak! Thanks for the pull

**Comment by MarconiGRF** [comment]
I can help looking for typing errors or wrong words or anything like that since Fibonacci accepted my help, just waiting for the assignment to do it so.

**Comment by dtzxporter** [comment]
@Fibonacci5813 Hi man, thanks for the pull. Can you do me a favor and backup your translations. Sync with master (To fix the /en folder) Then move yours to your language code folder /data/code/index/story/credits. That way we can add your language to the list!

**Comment by Fibonacci5813** [comment]
Ok i added the folder but i'm not quite sure i synced it properly with the master. Again i'm not very sure on how things work on github. Please tell me if i did it correctly. In regards to MarconiGRF, how do i go about sending you the files so you can help on the corrections? Or is it Porter that does it? Thanks gents

**Comment by dtzxporter** [comment]
The only thing you need to do (this is a workaround) Download my story and replace with your en one (it didn't update) just copy paste and the conflict will go away! Link: [Story EN](https://raw.githubusercontent.com/dtzxporter/Kronorium/master/data/en/story.json)

**Comment by dtzxporter** [comment]
PERFECT

**Comment by dtzxporter** [comment]
Merged.

**Pull request closed without merging**
